
services:
  frontend:
    image: frontend-image 
    build: 
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    image: api-image 
    build: 
      context: ./api
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/mydatabase
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

