
version: "3.8"

services:
  # API container
  api:
    build: ./api
    container_name: api-container
    volumes:
      - ./API:/app/API
      - ./Database:/app/Database
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  # Database container (MySQL)
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Only define this for root user password
      MYSQL_DATABASE: ${MYSQL_DATABASE}           # Database name to be created
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network


# Named volume for database persistence
volumes:
  db-data:

# Networks for communication between containers
networks:
  app-network:
    driver: bridge