services:
  # API container
  api:
    build: ./api
    container_name: api-container
    volumes:
      - ./API:/app/API
      - ./Database:/app/Database
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  # Database container (MySQL)
  database:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

# Networks for communication between containers
networks:
  app-network:
    driver: bridge