# Pull official base image
FROM python:3.11-slim

# Set work directory
WORKDIR /API/src

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copy requirements file
COPY requirements.txt /API/

# Install dependencies
RUN pip install --upgrade pip setuptools wheel \
    && pip install -r /API/requirements.txt \
    && rm -rf /root/.cache/pip

# Copy project files
COPY . /API/src

# Run the FastAPI application using uvicorn
CMD ["uvicorn", "src.app.main:tdlapp", "--host", "0.0.0.0", "--port", "8000"]
